# GitHub Pagesへのデプロイ用ワークフロー (pnpm版)

name: Deploy to GitHub Pages

# mainブランチにプッシュされた時にワークフローを実行
on:
  push:
    branches:
      - main

# ワークフローがリポジトリに書き込む権限を設定
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 最新のUbuntu環境で実行
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # プロジェクトで使用するNode.jsのバージョン

      # 3. pnpmをセットアップし、依存関係をインストール
      - name: Setup pnpm and Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          # 【変更】このアクション内でインストールを実行する
          run_install: true

      # 4. アプリケーションをビルド
      - name: Build
        # pnpm run build を実行
        run: pnpm run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}

      # 5. GitHub Pagesにデプロイ
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
